import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  SafeAreaView,
  Clipboard,
} from 'react-native';
import { Card, CardHeader, CardTitle, CardContent } from './ui/card.native';
import { Alert } from './ui/alert.native';
import { Input } from './ui/input.native';
import { Button } from './ui/button.native';
import { useToast } from './ui';

interface BackupCodesScreenNewProps {
  navigation: any;
  route: any;
}

export function BackupCodesScreenNew({ navigation, route }: BackupCodesScreenNewProps) {
  const { onVerifySuccess } = route.params || {};
  const { showToast } = useToast();
  const [backupCode, setBackupCode] = useState('');
  const [error, setError] = useState('');
  const [showCodes, setShowCodes] = useState(false);

  // Mock backup codes - in real app these would be generated by admin
  const mockBackupCodes = ['ABC123DEF', 'GHI456JKL', 'MNO789PQR', 'STU012VWX', 'YZ345ABC6'];

  const handleSubmit = () => {
    setError('');

    if (!backupCode.trim()) {
      setError('Please enter a backup code');
      return;
    }

    // Mock validation
    if (mockBackupCodes.includes(backupCode.toUpperCase())) {
      showToast('Backup code verified successfully!');
      if (onVerifySuccess) {
        onVerifySuccess();
      } else {
        navigation.navigate('RoleSelectionNew');
      }
    } else {
      setError('Invalid backup code. Please try again.');
      setBackupCode('');
    }
  };

  const copyToClipboard = (code: string) => {
    Clipboard.setString(code);
    showToast('Code copied to clipboard');
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => navigation.goBack()}
            style={styles.backButton}
            activeOpacity={0.7}
          >
            <Text style={styles.backIcon}>←</Text>
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Backup Codes</Text>
        </View>

        {/* Warning */}
        <View style={styles.warningSection}>
          <Alert
            variant="destructive"
            title="⚠️ Important"
            description="Use backup codes only when other verification methods are unavailable. Each code can only be used once."
          />
        </View>

        {/* Backup Code Input */}
        <View style={styles.inputSection}>
          <Card>
            <CardHeader>
              <CardTitle>Enter Backup Code</CardTitle>
            </CardHeader>
            <CardContent>
              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>9-Character Code</Text>
                <Input
                  placeholder="ABC123DEF"
                  value={backupCode}
                  onChangeText={(text) =>
                    setBackupCode(
                      text
                        .toUpperCase()
                        .replace(/[^A-Z0-9]/g, '')
                        .slice(0, 9)
                    )
                  }
                  style={styles.codeInput}
                  maxLength={9}
                  autoCapitalize="characters"
                />
              </View>

              {error ? (
                <Alert variant="destructive" description={error} style={styles.errorAlert} />
              ) : null}

              <Button onPress={handleSubmit} variant="default" style={styles.verifyButton}>
                <Text style={styles.verifyButtonText}>Verify Backup Code</Text>
              </Button>
            </CardContent>
          </Card>
        </View>

        {/* Available Codes (Demo) */}
        <View style={styles.codesSection}>
          <Card>
            <CardHeader>
              <View style={styles.codesHeader}>
                <CardTitle>Your Backup Codes</CardTitle>
                <TouchableOpacity
                  onPress={() => setShowCodes(!showCodes)}
                  style={styles.toggleButton}
                  activeOpacity={0.7}
                >
                  <Text style={styles.toggleIcon}>{showCodes ? '🙈' : '👁️'}</Text>
                </TouchableOpacity>
              </View>
            </CardHeader>
            <CardContent>
              {showCodes ? (
                <View>
                  <View style={styles.codesList}>
                    {mockBackupCodes.map((code, index) => (
                      <View key={index} style={styles.codeItem}>
                        <Text style={styles.codeText}>{code}</Text>
                        <TouchableOpacity
                          onPress={() => copyToClipboard(code)}
                          style={styles.copyButton}
                          activeOpacity={0.7}
                        >
                          <Text style={styles.copyIcon}>📋</Text>
                        </TouchableOpacity>
                      </View>
                    ))}
                  </View>
                  <Text style={styles.codesDescription}>
                    Store these codes securely. Print or save in a secure password manager.
                  </Text>
                </View>
              ) : (
                <View style={styles.codesHidden}>
                  <View style={styles.codesHiddenIcon}>
                    <Text style={styles.codesHiddenIconText}>👁️</Text>
                  </View>
                  <Text style={styles.codesHiddenText}>
                    Tap the eye icon to view your backup codes
                  </Text>
                </View>
              )}
            </CardContent>
          </Card>
        </View>

        {/* Actions */}
        <View style={styles.actionsSection}>
          <Button
            onPress={() => navigation.navigate('HelpNew')}
            variant="outline"
            style={styles.helpButton}
          >
            <Text style={styles.helpButtonText}>Lost your backup codes?</Text>
          </Button>
          <Text style={styles.actionsDescription}>
            Contact your administrator to generate new codes
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  backButton: {
    padding: 4,
    marginRight: 12,
  },
  backIcon: {
    fontSize: 24,
    color: '#1f2937',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
  },
  warningSection: {
    padding: 16,
  },
  inputSection: {
    padding: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 8,
  },
  codeInput: {
    textAlign: 'center',
    letterSpacing: 4,
    fontSize: 16,
    fontWeight: '600',
  },
  errorAlert: {
    marginBottom: 16,
  },
  verifyButton: {
    width: '100%',
  },
  verifyButtonText: {
    fontSize: 14,
    color: '#ffffff',
  },
  codesSection: {
    padding: 16,
  },
  codesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  toggleButton: {
    padding: 4,
  },
  toggleIcon: {
    fontSize: 20,
  },
  codesList: {
    gap: 12,
    marginBottom: 16,
  },
  codeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
  },
  codeText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    letterSpacing: 2,
  },
  copyButton: {
    padding: 4,
  },
  copyIcon: {
    fontSize: 20,
  },
  codesDescription: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
  },
  codesHidden: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  codesHiddenIcon: {
    width: 64,
    height: 64,
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  codesHiddenIconText: {
    fontSize: 32,
  },
  codesHiddenText: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  actionsSection: {
    padding: 16,
  },
  helpButton: {
    width: '100%',
    marginBottom: 16,
  },
  helpButtonText: {
    fontSize: 14,
    color: '#1f2937',
  },
  actionsDescription: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
});
